spring:
  application:
    name: fornecedor
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/fornecedor?allowPublicKeyRetrieval=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update